Simplify importing with 2018 features
dylanede/glsl-to-spirv-macros pull request #1
Opened 2019-02-02 07:20 UTC by swiftcoder

Rust 2018 gives us the tools we need to no longer expose the procmacro *-impl crate to consumers.

I'll be honest: I have no idea whether this is actually an idiomatic adoption of 2018 features. But it does succeed in making the impl crate truly an implementation detail, and that is a nice win in simplicity for those using the crate.

I'm afraid I also ran rustfmt on this, as that's my IDE default behaviour. The patch is a little less easy to review as a result.

2019-02-03 20:01 UTC, dylanede requested changes
I think Cargo.lock should be excluded. Generally that's only included in projects that have binaries or depend on nightly. Other than that and the small documentation changes suggested, this is a welcome PR. Thanks!

2019-02-03 20:01 UTC, dylanede commented on README.md
> +use glsl_to_spirv_macros::include_glsl_fs;
```suggestion
use glsl_to_spirv_macros::{glsl_vs, include_glsl_fs};
```

2019-02-03 20:01 UTC, dylanede commented on src/lib.rs
> +//! use glsl_to_spirv_macros::include_glsl_fs;
```suggestion
//! use glsl_to_spirv_macros::{glsl_vs, include_glsl_fs};
```

2019-02-04 00:46 UTC, swiftcoder commented
Right you are :) I forgot to update the .gitignore file for Cargo.lock

2019-09-17 03:54 UTC, swiftcoder commented
Thoughts on merging this in?

2024-06-25 13:57 UTC, closed without merging